config/routes.rb
Inventnet::Application.routes.draw do

  resources :topics do
    resources :contributors, only: [:index, :new, :delete, :create, :destroy]
    resources :ideas, except: :index
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root to: "home#index"

end

app/models/idea.rb
class Idea < ActiveRecord::Base
  belongs_to :topic
  belongs_to :user
  attr_accessible :content, :title

  validates_presence_of :topic, :user, :title
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_filter :authenticate_user!

  def show
    @topic = Topic.find(params[:topic_id])
    @idea = Idea.find(params[:id])

    respond_to do |format|
      if @topic.user_authorized?(current_user)
        format.html # show.html.erb
        format.json { render json: @idea }
      else
        flash[:alert] = "You are not authorized to see this topic!"
        format.html { redirect_to root_path }
      end
    end
  end

  def new
    @topic = Topic.find(params[:topic_id])
    @idea = Idea.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @idea }
    end
  end

  def edit
    @topic = Topic.find(params[:topic_id])
    @idea = Idea.find(params[:id])

    if !@topic.user_authorized?(current_user)
      flash[:alert] = "You are not authorized to edit ideas in this topic!"
      redirect_to root_path
      return
    end

    if @topic.owner != current_user && @idea.user != current_user
      flash[:alert] = "You are not authorized to edit this idea!"
      redirect_to root_path
    end
  end

  def create
    @topic = Topic.find(params[:topic_id])
    @idea = Idea.new(params[:idea])

    # Make sure the new idea belongs to the current user
    @idea.user = current_user
    @idea.topic = @topic

    if @idea.save then
      # Send notifications
      recipients = @topic.users + [@topic.owner]
      recipients.each do |r|
        Notifier.new_idea(r.email, @topic, @idea).deliver
      end
      redirect_to @topic, notice: 'Idea was successfully created.'
    else
      render action: "new"
    end
  end

  def update
    @topic = Topic.find(params[:topic_id])
    @idea = Idea.find(params[:id])

    respond_to do |format|
      if @idea.update_attributes(params[:idea])
        format.html { redirect_to @topic, notice: 'Idea was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  def destroy
    @topic = Topic.find(params[:topic_id])
    @idea = Idea.find(params[:id])
    @idea.destroy

    respond_to do |format|
      format.html { redirect_to @topic, notice: 'Idea was successfully deleted.' }
    end
  end
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/views/ideas/_form.html.erb
<%= simple_form_for [@topic, @idea], :html => {:class => 'form-horizontal'} do |f| %>
    <fieldset>
      <legend><%= controller.action_name.capitalize %> Idea</legend>
      <br/>
      <div class="alert alert-info">
        You can use <a target="_blank" href="http://github.github.com/github-flavored-markdown/">github flavored Markdown</a> in your note.
      </div>

      <%= f.input :title -%>
      <%= f.input :content -%>


      <div class="form-actions">
        <%= f.button :submit, class: 'btn btn-primary' %>
        <%= link_to 'Cancel', topic_path(@topic), :class => 'btn' %>
      </div>
    </fieldset>
<% end %>

app/views/ideas/edit.html.erb
<%= render :partial => 'form' %>

app/views/ideas/index.html.erb
<h1>Ideas</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>Title</th>
      <th>Created at</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @ideas.each do |idea| %>
      <tr>
        <td><%= idea.id %></td>
        <td><%= link_to idea.title, idea_path(idea) %></td>
        <td><%= idea.created_at %></td>
        <td>
          <%= link_to 'Edit', edit_idea_path(idea), :class => 'btn btn-mini' %>
          <%= link_to 'Destroy', idea_path(idea), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New', new_idea_path, :class => 'btn btn-primary' %>

app/views/ideas/new.html.erb
<%= render :partial => 'form' %>

app/views/ideas/show.html.erb
<div class="page-header"><h1>Idea</h1></div>

<p>
  <b>Topic</b><br>
  <%= @topic.title %>
</p>

<p>
  <b>Title</b><br>
  <%= @idea.title %>
</p>

<hr/>
<b>Content</b>
<div class="well well-small">
  <%= markdown @idea.content %>
</div>

<div class="form-actions">
  <%= link_to '<i class="icon-arrow-left"></i> Back'.html_safe, topic_path(@topic), :class => 'btn' %>
  <%- if @idea.user == current_user || @topic.owner == current_user -%>
      <%= link_to '<i class="icon-edit"></i> Edit'.html_safe, edit_topic_idea_path(@topic, @idea), :class => 'btn' %>
      <%= link_to '<i class="icon-trash"></i> Delete'.html_safe, topic_idea_path(@topic, @idea), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-danger' %>
  <%- end -%>
</div>