config/routes.rb
Inventnet::Application.routes.draw do

  resources :topics do
    resources :contributors, only: [:index, :new, :delete, :create, :destroy]
    resources :ideas, except: :index
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root to: "home#index"

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :owner, class_name: "User"
  has_many :ideas, dependent: :destroy
  has_many :roles, dependent: :destroy
  has_many :users, through: :roles

  attr_accessible :abstract, :title

  validates_presence_of :title, :owner
  
  def self.find_by_authorized_user(user)
    roles = Role.where user_id: user.id

    result = self.where(owner_id: user.id)
    roles.each do |r|
      result += self.where(id: r.topic_id)
    end
    
    result

  end
  
  def user_authorized?(user)
    if self.owner == user || self.users.include?(user)
      true
    else
      false
    end
  end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_filter :authenticate_user!

  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @topics }
    end
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
    @topic = Topic.find(params[:id])

    respond_to do |format|
      if @topic.user_authorized?(current_user)
        format.html # show.html.erb
        format.json { render json: @topic }
      else
        flash[:alert] = "You are not authorized to see this topic!"
        format.html { redirect_to root_path }
      end
    end
  end

  # GET /topics/new
  # GET /topics/new.json
  def new
    @topic = Topic.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @topic }
    end
  end

  # GET /topics/1/edit
  def edit
    @topic = Topic.find(params[:id])
    if !@topic.user_authorized?(current_user)
      flash[:alert] = "You are not authorized to edit this topic!"
      redirect_to root_path
    end
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(params[:topic])

    # Make sure the new topic belongs to the current user
    @topic.owner = current_user

    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: 'Topic was successfully created.' }
        format.json { render json: @topic, status: :created, location: @topic }
      else
        format.html { render action: "new" }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @topic = Topic.find(params[:id])

    # Check if the current user is the owner
    if @topic.owner != current_user then
      sign_out current_user
      flash[:alert] = "You can't modify a topic which does not belong to you!"
      redirect_to new_user_session_path
      return
    end

    respond_to do |format|
      if @topic.update_attributes(params[:topic])
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @topic = Topic.find(params[:id])

    # Check if the current user is the owner
    if @topic.owner != current_user then
      sign_out current_user
      flash[:alert] = "You can't delete a topic which does not belong to you!"
      redirect_to new_user_session_path
      return
    end

    @topic.destroy

    respond_to do |format|
      format.html { redirect_to topics_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<%= simple_form_for @topic, :html => {:class => 'form-horizontal'} do |f| %>
    <legend><%= controller.action_name.capitalize %> Topic</legend>

    <%= f.input :title %>
    <%= f.input :abstract, :class => 'control-label' %>

    <div class="form-actions">
      <%= f.button :submit, class: 'btn btn-primary' %>
      <%= link_to 'Cancel', topics_path, :class => 'btn' %>
    </div>

<% end %>

app/views/topics/edit.html.erb
<%= render :partial => 'form' %>

app/views/topics/index.html.erb
<h1>Topics</h1>
<table class="table table-striped">
  <thead>
  <tr>
    <th>Title</th>
    <th>Created on</th>
    <th>Actions</th>
  </tr>
  </thead>
  <tbody>
  <% @topics.each do |topic| %>
      <%- if (topic.users + [topic.owner]).include? current_user -%>
          <tr>
            <td><i class="icon-inbox"></i> <%= link_to topic.title, topic_path(topic) %></td>
            <td><%= topic.created_at.to_date.to_formatted_s(:long) %></td>
            <td>
              <%- if topic.owner == current_user -%>
                  <%= link_to '<i class="icon-edit"></i> Edit'.html_safe, edit_topic_path(topic), :class => 'btn btn-mini' %>
                  <%= link_to '<i class="icon-trash"></i> Delete'.html_safe, topic_path(topic), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger' %>
              <%- else -%>
                  <i>You are not the owner</i>
              <%- end -%>

            </td>
          </tr>
      <%- end -%>
  <% end %>
  </tbody>
</table>

<%= link_to '<i class="icon-file"></i> New'.html_safe, new_topic_path, :class => 'btn btn-primary' %>

app/views/topics/new.html.erb
<%= render :partial => 'form' %>

app/views/topics/show.html.erb
<div class="page-header" xmlns="http://www.w3.org/1999/html"><h1><%= @topic.title -%></h1></div>

<div class="alert alert-info">
  <%- if @topic.abstract != "" -%>
      <p>
        <b>Abstract</b><br>
        <%= simple_format @topic.abstract %>
      </p>
  <%- end -%>

  <p>
    <b>Owner</b><br>
    <%- if current_user == @topic.owner -%>
        <i class="icon-user"></i> Me
    <%- else -%>
        <i class="icon-user"></i> <%= @topic.owner.email %>
    <%- end -%>
  </p>

  <%- if @topic.users.count > 0 -%>
      <p>
        <b>Contributors</b><br/>
        <%- @topic.users.each do |u| -%>
            <i class="icon-user"></i> <%= u.email -%><br/>
        <%- end -%>
      </p>
  <%- end -%>
</div>


<div class="page-header"><h2>Ideas</h2></div>
<% @ideas = Idea.where(topic_id: @topic) %>
<%- if @ideas.count > 0 -%>
    <table class="table table-striped">
      <thead>
      <tr>
        <th>Title</th>
        <th>Created on</th>
        <th>By</th>
        <th>Actions</th>
      </tr>
      </thead>
      <tbody>
      <% @ideas.each do |idea| %>
          <tr>
            <td><i class="icon-file"></i> <%= link_to idea.title, topic_idea_path(@topic, idea) %></td>
            <td><%= idea.created_at.to_date.to_formatted_s(:long) %></td>
            <td><%= idea.user.email -%></td>
            <td>
              <%- if idea.user == current_user || @topic.owner == current_user -%>
                  <%= link_to '<i class="icon-edit"></i> Edit'.html_safe, edit_topic_idea_path(@topic, idea), :class => 'btn btn-mini' %>
                  <%= link_to '<i class="icon-trash"></i> Delete'.html_safe, topic_idea_path(@topic, idea), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger' %>
                 <%- else -%>
              <i class="icon-ban-circle"></i> <i>Not your idea</i>
              <%- end -%>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>
<%- else -%>
    <p>No ideas yet in this topic…</p>
<%- end -%>

<%= link_to '<i class="icon-file"></i> New Idea!'.html_safe, new_topic_idea_path(@topic), :class => 'btn btn-primary' %>

<div class="form-actions">
  <%= link_to '<i class="icon-arrow-left"></i> Back'.html_safe, topics_path, :class => 'btn' %>
  <%- if current_user == @topic.owner -%>
      <%= link_to '<i class="icon-edit"></i> Edit'.html_safe, edit_topic_path(@topic), :class => 'btn' %>
      <%= link_to '<i class="icon-user"></i> Contributors'.html_safe, topic_contributors_path(@topic), class: 'btn btn-inverse' %>
      <%= link_to '<i class="icon-trash"></i> Delete'.html_safe, topic_path(@topic), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-danger' %>
  <%- end -%>
</div>