config/routes.rb
Inventnet::Application.routes.draw do

  resources :topics do
    resources :contributors, only: [:index, :new, :delete, :create, :destroy]
    resources :ideas, except: :index
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root to: "home#index"

end

app/controllers/contributors_controller.rb
class ContributorsController < ApplicationController
  before_filter :authenticate_user!

  def index
    @topic = Topic.find(params[:topic_id])
    @contributors = @topic.users

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @contributors }
    end
  end

  def new
    @contributor = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @contributor }
    end
  end

  def create
    @contributor = params[:user][:email]
    @topic = Topic.find params[:topic_id]

    if User.where("email='#{@contributor}'").count == 1
      user = User.where("email='#{@contributor}'").first

      if @topic.users.include? user then
        redirect_to topic_contributors_path, alert: "User #{@contributor} is already a contributor!"
      elsif @topic.owner == user
        redirect_to topic_contributors_path, alert: "User #{@contributor} is the owner of this topic!"
      else
        @topic.users << user
        redirect_to topic_contributors_path, notice: "Contributor #{@contributor} was successfully added."
      end
    else
      flash[:alert] = "There are no users with email #{@contributor}. Ask them to register!"
      render action: "new"
    end
  end

  def destroy
    topic = Topic.find(params[:topic_id])
    user = topic.users.find(params[:id])
    role = Role.where("user_id = ? AND topic_id = ?", user.id, topic.id)[0]

    role.destroy

    respond_to do |format|
      flash[:notice] = "Contributor successfully removed."
      format.html { redirect_to topic_contributors_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/contributors_helper.rb
module ContributorsHelper
end

app/views/contributors/index.html.erb
<h1>Contributors for <%= @topic.title -%></h1>

<table class="table table-striped">
  <thead>
  <tr>
    <th>Email</th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @contributors.each do |contributor| %>
      <tr>
        <td><%= contributor.email -%></td>
        <%- if @topic.owner == current_user -%>
            <td><%= link_to 'Remove', topic_contributor_path(@topic, contributor), confirm: 'Are you sure?', method: :delete, class: 'btn btn-mini btn-danger' %></td>
        <%- end -%>
      </tr>
  <% end %>
  </tbody>
</table>

<br/>

<%= link_to 'New Contributor', new_topic_contributor_path(@topic), class: "btn btn-primary" %>
<%= link_to 'Back', topic_path(@topic), class: "btn" %>

app/views/contributors/new.html.erb
<h1>New contributor</h1>
<br/>
<%= simple_form_for @contributor, url: topic_contributors_path, html: {class: "form-horizontal"} do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :email %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Add", class: "btn btn-primary" %>
    <%= link_to 'Cancel', topic_contributors_path, :class => 'btn' %>
  </div>
<% end %>